language: node_js
node_js:
  - '0.10'
before_install:
  - 'gem install compass'
  - 'export DISPLAY=:99.0'
  - 'sh -e /etc/init.d/xvfb start'
before_script:
  - 'npm install -g bower grunt-cli karma-cli'
  - 'bower install'
